# Generated by Django 5.2.7 on 2025-10-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_accademique', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('annee_encours', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Années Académiques',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Filières',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACTUEL', 'Contractuel'), ('VACATAIRE', 'Vacataire')], default='PERMANENT', max_length=20)),
                ('domaine_enseignement', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Professeurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MatiereProgrammee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_heure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_debut_estimee', models.DateField(blank=True, null=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.anneeacademique')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.matiere')),
            ],
            options={
                'verbose_name_plural': 'Matières Programmées',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evaluation', models.CharField(max_length=50)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('matiere_programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.matiereprogrammee')),
            ],
            options={
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('niv', models.IntegerField(default=1)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.filiere')),
            ],
            options={
                'verbose_name_plural': 'Niveaux',
                'unique_together': {('libelle', 'filiere', 'niv')},
            },
        ),
        migrations.AddField(
            model_name='matiereprogrammee',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.niveau'),
        ),
        migrations.AddField(
            model_name='matiereprogrammee',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.professeur'),
        ),
        migrations.CreateModel(
            name='Emargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emar', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('heure_eff', models.DecimalField(decimal_places=2, max_digits=4)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('matiere_programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.matiereprogrammee')),
            ],
            options={
                'verbose_name_plural': 'Émargements',
                'unique_together': {('matiere_programmer', 'date_emar')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='matiereprogrammee',
            unique_together={('matiere', 'filiere', 'niveau', 'annee_academique')},
        ),
    ]
