# Generated by Django 5.2.7 on 2025-10-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emargement',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='emargement',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='emargement',
            name='heure_fin',
        ),
    ]
