# Generated by Django 5.2.7 on 2025-10-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0002_remove_emargement_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiereprogrammee',
            name='date_fin_estimee',
            field=models.DateField(blank=True, null=True),
        ),
    ]
