# Generated by Django 5.2.7 on 2025-10-17 10:33 (Mise à jour pour inclure RunSQL)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Note: Les fonctions Python set_matiere_code et set_professeur_contact sont supprimées car 
# RunSQL est utilisé pour l'initialisation des données uniques.

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0004_remove_evaluation_coefficient_remove_evaluation_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- BLOC DE SUPPRESSION (Initialement présent) ---
        migrations.RemoveField(
            model_name='anneeacademique',
            name='annee_encours',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='domaine_enseignement',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='status',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='telephone',
        ),

        # ----------------------------------------------------------------------
        # --- OPÉRATIONS DE CORRECTION POUR MATIERE.CODE (UNIQUE, NON-NULLABLE) ---
        # ----------------------------------------------------------------------
        
        # 1. Ajoutez le champ 'code', temporairement NULLABLE
        migrations.AddField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        
        # 2. Exécutez le script SQL pour garantir des valeurs uniques et non-nulles
        migrations.RunSQL(
            # SQL pour SQLite : Met à jour 'code' avec 'MAT_' suivi de l'ID pour garantir l'unicité
            """
            UPDATE gestion_cours_matiere
            SET code = 'MAT_' || id
            WHERE code IS NULL OR code = '';
            """,
            reverse_sql=migrations.RunPython.noop # Pas de retour en arrière pour cette étape
        ),

        # 3. Rendez le champ 'code' NON-NULLABLE
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=20, unique=True), # null=False par défaut
        ),

        # -------------------------------------------------------------------------
        # --- OPÉRATIONS DE CORRECTION POUR PROFESSEUR.CONTACT (UNIQUE, NON-NULLABLE) ---
        # -------------------------------------------------------------------------

        # 4. Ajoutez le champ 'contact', temporairement NULLABLE
        migrations.AddField(
            model_name='professeur',
            name='contact',
            field=models.CharField(max_length=50, null=True, unique=True), # max_length de 50 pour le contact
        ),

        # 5. Exécutez la correction SQL des données pour le contact
        migrations.RunSQL(
            # SQL pour SQLite : Met à jour 'contact' avec une série de zéros + l'ID pour garantir l'unicité
            """
            UPDATE gestion_cours_professeur
            SET contact = '0000000' || id
            WHERE contact IS NULL OR contact = '';
            """,
            reverse_sql=migrations.RunPython.noop
        ),

        # 6. Rendez le champ 'contact' NON-NULLABLE
        migrations.AlterField(
            model_name='professeur',
            name='contact',
            field=models.CharField(max_length=50, unique=True), # null=False par défaut
        ),

        # --- BLOC D'AJOUT ET D'ALTÉRATION (Autres opérations initialement présentes) ---
        
        # Ajout du champ utilisateur_evaluation
        migrations.AddField(
            model_name='evaluation',
            name='utilisateur_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Évalué par'),
        ),
        
        # Les autres AlterField
        migrations.AlterField(
            model_name='anneeacademique',
            name='annee_accademique',
            field=models.CharField(max_length=15, unique=True), # Max length ajustée à 15
        ),
        migrations.AlterField(
            model_name='emargement',
            name='date_emar',
            field=models.DateField(verbose_name='Date de la séance'),
        ),
        migrations.AlterField(
            model_name='emargement',
            name='heure_eff',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Heures effectuées'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='matiere_programmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.matiereprogrammee'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matiereprogrammee',
            name='nbr_heure',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Volume horaire prévu'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='libelle',
            field=models.CharField(choices=[('Licence', 'Licence'), ('Master', 'Master')], max_length=10),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='niv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='prenoms',
            field=models.CharField(max_length=150),
        ),
    ]