# Generated by Django 5.2.7 on 2025-10-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0005_remove_anneeacademique_annee_encours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeacademique',
            name='annee_accademique',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
