# Generated by Django 5.2.7 on 2025-10-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0006_alter_anneeacademique_annee_accademique_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matiereprogrammee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matiereprogrammee',
            name='semestre',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], default='S1', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='matiereprogrammee',
            unique_together={('matiere', 'filiere', 'niveau', 'annee_academique', 'semestre')},
        ),
    ]
