# Generated by Django 5.2.7 on 2025-10-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0007_alter_matiereprogrammee_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professeur',
            options={'ordering': ['nom'], 'verbose_name': 'Professeur', 'verbose_name_plural': 'Professeurs'},
        ),
        migrations.AddField(
            model_name='professeur',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='professeurs/cvs/', verbose_name='CV (Fichier)'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='dernier_diplome',
            field=models.FileField(blank=True, null=True, upload_to='professeurs/diplomes/', verbose_name='Dernier Diplôme (Fichier)'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='domaine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Domaine d'expertise"),
        ),
        migrations.AddField(
            model_name='professeur',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grade universitaire'),
        ),
    ]
